// =============== Import Sections ===============

import type { Metadata } from "next";
import "./globals.css";
import RQProvider from "@/context/RQProvider";
import AppContext from "@/context/appContext";

export const metadata: Metadata = {
  title: "فروشگاه اینترنتی سبحان کالا😉",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="" href="./icons/css/all.min.css" />
      </head>

      <body>
        <AppContext>
          <RQProvider>{children}</RQProvider>
        </AppContext>
      </body>
    </html>
  );
}
