import type { Metadata } from "next";
import "./globals.css";
import AppContextProvider from "@/context/appContext";
import RQProvider from "@/service/reactQueryProvider/RQProvider";
import AppContext from "@/context/appContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="stylesheet" href="./icons/css/all.min.css" />
      </head>

      <body>
        <AppContext>
          <RQProvider>{children}</RQProvider>
        </AppContext>
      </body>
    </html>
  );
}
